language: node_js
node_js:
  - "10" # ends April 2021

sudo: required

script:
  - yarn install
  - yarn ci
  - if [[ $TRAVIS_REPO_SLUG == "noelyoo/learn-scilla" && $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      yarn build;
      yarn global add firebase-tools typescript tslint;
      firebase use default;
      firebase deploy --token $FIREBASE_TOKEN --non-interactive;
    fi
    