version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing source NPM dependencies...
      - npm i npm@latest -g
      - npm install -g yarn
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - yarn install
      - yarn validate
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build